default_language_version:
  python: python3

exclude: ^(venv)/

repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
      - id: seed-isort-config

  - repo: git://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-builtin-literals
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: flake8
      - id: check-ast

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
